# Generated by Django 3.1.1 on 2020-11-12 20:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.city')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.CharField(max_length=7)),
                ('building', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('cover_pic', models.ImageField(upload_to='photos/cover')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(100000)])),
                ('tenant_type', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Family Only', 'Family Only'), ('Any', 'Any')], max_length=30)),
                ('deposit', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(1000000)])),
                ('furnished', models.CharField(choices=[('Unfurnished', 'Unfurnished'), ('Semi furnished', 'Semi furnished'), ('Furnished', 'Unfurnished')], max_length=30)),
                ('club_house', models.BooleanField()),
                ('swimming_pool', models.BooleanField()),
                ('security', models.BooleanField()),
                ('ac', models.BooleanField()),
                ('gym', models.BooleanField()),
                ('lift', models.BooleanField()),
                ('play_area', models.BooleanField()),
                ('internet_services', models.BooleanField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.city')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.locality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
